version: '3'

services:
  portainer:
    image: portainer/portainer:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/var/lib/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-net
  
volumes:
  portainer-data:

networks:
  portainer-net:
    driver: bridge