version: '3.4'

networks:
  odoo-14-net:
    driver: bridge

volumes:
  odoo-14-db-postgresql:
  odoo-14-db-pgadmin4:
  odoo-14-filestore:

services:
  app:
    build: 
      context: ../.
      dockerfile: Dockerfile
    volumes:
      - odoo-14-filestore:/var/lib/odoo
      - ../.devcontainer:/usr/lib/python3/dist-packages/odoo/.devcontainer
      - ../.vscode:/usr/lib/python3/dist-packages/odoo/.vscode
      - ../data-dir:/usr/lib/python3/dist-packages/odoo/data-dir
      - ../extra-addons:/usr/lib/python3/dist-packages/odoo/extra-addons
      - ../config/odoo:/etc/odoo
      - ../config/odoo/odoo.conf:/usr/lib/python3/dist-packages/odoo/odoo.conf
    networks:
      - odoo-14-net
    depends_on:
      - db
    ports:
      - 8069:8069
      - 8072:8072
    tty: true
    command: ["/bin/bash"]

  db:
    user: root
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-14-db-postgresql:/var/lib/postgresql/data
    networks:
      - odoo-14-net
  pgadmin4:
    user: root
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@odoo.com.br
      PGADMIN_DEFAULT_PASSWORD: odoo@2023
    ports:
      - "8080:80"
    networks:
      - odoo-14-net
    volumes:
      - odoo-14-db-pgadmin4:/var/lib/pgadmin4/data
    depends_on:
      - db
